#!/usr/bin/env node
/**
 * Reads the project's canonical markdown files from docs/ and writes a
 * TypeScript module that exports them as string literals. Run BEFORE
 * `next build` via the npm `prebuild` / `predev` lifecycle hooks.
 *
 * Why bake instead of read-at-runtime:
 *   - Vercel/Dokku's bundler only ships files statically referenced from
 *     the build output. A `readFileSync` of a path computed at runtime
 *     is not analyzable and the docs may not end up in the bundle.
 *   - Baking the content into a `.ts` file makes it a normal import.
 *     The bundler ships the strings into the route bundle for free.
 *   - One source of truth: docs/ in the monorepo. The generated module
 *     is git-ignored.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
// scripts/ → apps/cloud-web/ → apps/ → repo root
const repoRoot = join(here, "..", "..", "..");
const docsDir = join(repoRoot, "docs");

const SOURCES = [
  { slug: "introduction", file: "introduction.md" },
  { slug: "installation", file: "installation.md" },
  { slug: "integration",  file: "integration.md"  },
  { slug: "security",     file: "security.md"     },
  { slug: "reference",    file: "reference.md"    },
];

const baked = {};
for (const { slug, file } of SOURCES) {
  const path = join(docsDir, file);
  try {
    baked[slug] = readFileSync(path, "utf8");
  } catch (err) {
    console.error(`[bake-docs] could not read ${path}: ${err.message}`);
    baked[slug] = "";
  }
}

const outDir = join(here, "..", "src", "lib", "generated");
mkdirSync(outDir, { recursive: true });

// REFERENCE_MD export stays for backward compat with the older
// /docs page that was wired before the full docs viewer was ported.
const body =
  "// AUTO-GENERATED by scripts/bake-docs.mjs — do not edit by hand.\n" +
  "// Source: docs/*.md in the monorepo root.\n" +
  "// Regenerate: pnpm --filter @authai/cloud-web run bake:docs\n\n" +
  `export const REFERENCE_MD: string = ${JSON.stringify(baked.reference ?? "")};\n\n` +
  "export const DOCS: Record<string, string> = " +
  JSON.stringify(baked, null, 2) +
  ";\n";

const outPath = join(outDir, "reference-md.ts");
writeFileSync(outPath, body);

const totalChars = Object.values(baked).reduce((n, s) => n + s.length, 0);
console.log(
  `[bake-docs] wrote ${outPath} — ${SOURCES.length} files, ${totalChars} chars total`,
);
